dist: xenial
language: node_js
node_js:
- node
- '9.11.1'

before_install:
- openssl aes-256-cbc -K $encrypted_4cedf54ac66a_key -iv $encrypted_4cedf54ac66a_iv
  -in client-secret.json.enc -out client-secret.json -d

deploy:
  provider: gae
  keyfile: client-secret.json
  project: ri-app
  on: production