dist: xenial
language: node_js
node_js:
- node
- 9.11.1
before_install:
- openssl aes-256-cbc -K $encrypted_2a5cc5fd656c_key -iv $encrypted_2a5cc5fd656c_iv
  -in client-secret.json.enc -out client-secret.json -d

deploy:
  provider: gae
  keyfile: client-secret.json
  project: ri-app-1
