
version: '3.2'

services:

  graphite-statsd:
      container_name: real_ignite_service_graphite_statsd
      image: hopsoft/graphite-statsd
      env_file:
        - ./.env
      ports:
        - "9000:80/tcp"
        - "2003"
        - "2004"
        - "2023"
        - "2024"
        - "8125"
        - "8126"
      networks:
        - main_network

  mysql:
    container_name: real_ignite_service_mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file:
        - ./.env
    ports:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: "user"
        MYSQL_PASSWORD: "pass"
        MYSQL_DATABASE: "db"
        default_authentication_plugin: "mysql_native_password"
    networks:
        - main_network

  redis:
    container_name: real_ignite_service_redis
    image: redis
    env_file:
        - ./.env
    ports:
        - "6379"
    networks:
        - main_network
  
networks:
  main_network:
    driver: bridge